### ISSUE TITLE
A bug with dask computation

### ISSUE THREAD

**Issue by Koni2020** [josuemtzmo/xarrayMannKendall#10]
1. **What happend?**

Helleo, I try to calculate slope with xarrayMannKendall package. However, I find the result is wrong 

> (![e444ac0d74e20518203090523753e62](https://user-images.githubusercontent.com/74965981/197902888-d23ee764-624d-45e5-9fd8-ff4a4f04039b.png)). The slope matrix exhibits regular nan value compared by origin matrix. How to  solve it? Thanks.

2. **Possible casue**

The origin code of dask compute in package seems to not be used full cpu core. Therefore, I try to pass the ’scheduler='processes'‘ into the dask compute function. Furthermore, I recommend adding a Progresser bar to better monitor the progress of computation.

**Comment by josuemtzmo** [comment]
Hello @Koni2020, could you share the code to reproduce the issue? Does passing the `scheduler='processes'` solves the issue?

**Comment by Koni2020** [comment]
**1. Overview**
@josuemtzmo I'm very sorry for comment yesterday that the wrong result is caused by my wrong dataset. Yeasterday, I found the `dask.compute` don't use full cpu core. When I used the `processes` scheduler  to bypass GIL, I found the reuslt was wrong, albeit speeded up. I thought the wrong result that exhibited regular nan values was caused by `processes` , I found it caused by my wrong dataset later. Therefore, I recommend computing with the scheduler 'processes'.

**2. Reason**
The default  scheduler of dask.array object is ['threaded'](https://docs.dask.org/en/stable/scheduler-overview.html?highlight=dask.multiprocessing.get#scheduler-overview). However, due to the Python's GIL, it only provides parallelism if your computation is dominated by **non-Python** [code](https://docs.dask.org/en/stable/shared.html). Therefore, I try to use the 'processes' to bypass issues with the [GIL](https://docs.dask.org/en/stable/scheduler-overview.html?highlight=dask.multiprocessing.get#scheduler-overview) . The reuslt indicates that 'processes' is faster than 'threads' in the fllowing code. 

**3. Code**
```
import numpy as np
import xarray as xr
import xarrayMannKendall

if __name__ == "__main__":
    data_arr = xr.DataArray(np.random.randn(500, 500, 60), dims=['y', 'x', 'time'],
                      coords={'y': np.arange(500), 'x': np.arange(500), 'time': np.arange(60)})
    data_arr = data_arr.chunk({'x': 100, 'y': 100})
    mk_class = xarrayMannKendall.Mann_Kendall_test(data_arr, alpha=0.05, dim='time', method='theilslopes')
    mk_result_process = mk_class.compute(scheduler='threading')
    mk_result_threads = mk_class.compute(scheduler='multiprocessing')
   

@check_if_file_exists
def compute(self,save=False,path=None,rewrite_trends=True, scheduler='threads'):
  try:
      from dask.diagnostics import ProgressBar, Profiler, ResourceProfiler, CacheProfiler, visualize
  except:
      pass

  trend_method=self.xarray_MK_trend()
  with Profiler() as prof, ResourceProfiler() as rprof, CacheProfiler() as cprof, ProgressBar():
      MK_output = trend_method.compute(scheduler=scheduler)

  visualize([prof, rprof, cprof])
  if len(self.ordered_dims) == 2:
      ds = xr.Dataset({'trend': (['x'], MK_output[:,0]),
                   'signif': (['x'], MK_output[:,1]),
                   'p': (['x'], MK_output[:,2]),
                   'std_error': (['x'], MK_output[:,3])
                  },
                  coords={'x': (['x'], da2py(self.DataArray.x, False))})
  else:
      ds = xr.Dataset({'trend': (['y', 'x'], MK_output[:,:,0]),
                   'signif': (['y', 'x'], MK_output[:,:,1]),
                   'p': (['y', 'x'], MK_output[:,:,2]),
                   'std_error': (['y', 'x'], MK_output[:,:,3])
                  },
                  coords={'x': (['x'], da2py(self.DataArray.x,False)),
                          'y': (['y'], da2py(self.DataArray.y,False))})
  if path != None:
      ds.to_netcdf(path)
  elif save and path == None:
      ds.to_netcdf('./tmp.nc')
  return ds

```

**Comment by josuemtzmo** [comment]
For reference, the following issue is related to this one:
https://github.com/Koni2020/SWFU/issues/1

**Comment by josuemtzmo** [comment]
Hello @Koni2020, 

I've done a benchmark using the `multiprocessing`, `threading`, and `distributed` (default configuration in dask). As you can see on the figure bellow (x axis: side of dataset; y axis: time), I can't find a memory improvement when using lazy loading. I agree that there seems to be a speed improvement if the dataset used fits within memory, but generally that can be a bottleneck when using datasets larger than a few Gb. I will add the option to pass the scheduler, but by default the scheduler will remain to be `distributed`.
 
![speed_test](https://user-images.githubusercontent.com/9144063/199437416-f096323b-075c-4320-83f0-80aa08cabf95.png)

**Comment by josuemtzmo** [comment]
#11 adds support to the requested feature.
