### ISSUE TITLE
Using a DataArray object to construct a variable is ambiguous

### ISSUE THREAD

**Issue by NILICK** [josuemtzmo/xarrayMannKendall#4]
I have a data array that includes monthly drought SPEI index for January month in 20 years. This data array was clipped base on study area, so it has nodata values in out of study area. By useing xarrayMannKendall for mapping trend of this data, it return below error. How can I solve this problem.

`# SPEI January dataarray`

`spei_jan_`
`<xarray.DataArray 'spei' (time: 21, latitude: 501, longitude: 721)>`
`array([[[nan, nan, ..., nan, nan],`
       ` [nan, nan, ..., nan, nan],`
      `  ...,`
      `  [nan, nan, ..., nan, nan],`
     `   [nan, nan, ..., nan, nan]],`

     ` [[nan, nan, ..., nan, nan],`
      `  [nan, nan, ..., nan, nan],`
      `  ...,`
      `  [nan, nan, ..., nan, nan],`
      ` [nan, nan, ..., nan, nan]],`

    `  ...,`

      ` [[nan, nan, ..., nan, nan],`
      `  [nan, nan, ..., nan, nan],`
     `   ...,`
      `  [nan, nan, ..., nan, nan],`
    `    [nan, nan, ..., nan, nan]],`

     `  [[nan, nan, ..., nan, nan],`
       ` [nan, nan, ..., nan, nan],`
      `  ...,`
      `  [nan, nan, ..., nan, nan],`
      `  [nan, nan, ..., nan, nan]]], dtype=float32)``
`Coordinates:`
 ` * time       (time) datetime64[ns] 2000-03-31 2001-03-31 ... 2020-03-31`
 ` * latitude   (latitude) float64 27.0 27.01 27.02 27.03 ... 31.98 31.99 32.0`
` * longitude  (longitude) float64 49.8 49.81 49.82 49.83 ... 56.98 56.99 57.0`
 
 `# plotting one month for example`
`spei_jan_[15].plot();`

`spei_jan_[15].plot();`

![image](https://user-images.githubusercontent.com/65063089/141695879-f0200242-e15c-43b9-b373-5b6153cf48f9.png)

`tke_trends = Mann_Kendall_test(spei_jan_,'time',MK_modified=True,   method="linregress",alpha=0.05,  coords_name = {'time':'time','x':'latitude','y':'longitude'})`

`speijan_trends = tke_trends.compute()`

# Error

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/tmp/ipykernel_225096/3265428613.py in <module>
----> 1 speijan_trends = tke_trends.compute()

~/Downloads/xarrayMannKendall-master/xarrayMannKendall/xarrayMannKendall.py in compute(self, save, path)
    215                         coords={'x': (['x'], self.DataArray.x)})
    216         else:
--> 217             ds = xr.Dataset({'trend': (['y', 'x'], MK_output[:,:,0]),
    218                          'signif': (['y', 'x'], MK_output[:,:,1]),
    219                          'p': (['y', 'x'], MK_output[:,:,2]),

~/.local/lib/python3.9/site-packages/xarray/core/dataset.py in __init__(self, data_vars, coords, attrs)
    752             coords = coords.variables
    753 
--> 754         variables, coord_names, dims, indexes, _ = merge_data_and_coords(
    755             data_vars, coords, compat="broadcast_equals"
    756         )

~/.local/lib/python3.9/site-packages/xarray/core/merge.py in merge_data_and_coords(data, coords, compat, join)
    481     objects = [data, coords]
    482     explicit_coords = coords.keys()
--> 483     indexes = dict(_extract_indexes_from_coords(coords))
    484     return merge_core(
    485         objects, compat, join, explicit_coords=explicit_coords, indexes=indexes

~/.local/lib/python3.9/site-packages/xarray/core/merge.py in _extract_indexes_from_coords(coords)
    490     """Yields the name & index of valid indexes from a mapping of coords"""
    491     for name, variable in coords.items():
--> 492         variable = as_variable(variable, name=name)
    493         if variable.dims == (name,):
    494             yield name, variable._to_xindex()

~/.local/lib/python3.9/site-packages/xarray/core/variable.py in as_variable(obj, name)
    119     elif isinstance(obj, tuple):
    120         if isinstance(obj[1], DataArray):
--> 121             raise TypeError(
    122                 "Using a DataArray object to construct a variable is"
    123                 " ambiguous, please extract the data using the .data property."

TypeError: Using a DataArray object to construct a variable is ambiguous, please extract the data using the .data property.`

**Comment by NILICK** [comment]
I solved this problem with downgrade xarray to 0.18.2. I hope the original code improves to the new version of xarray.

**Comment by josuemtzmo** [comment]
Hello @NILICK, sorry for the slow reply (I just started a new position). I will have a look into this to make it forward compatible with `xarray` 0.18.2. Please let me know if you find any problem.

**Comment by NILICK** [comment]
> Hello @NILICK, sorry for the slow reply (I just started a new position). I will have a look into this to make it forward compatible with `xarray` 0.18.2. Please let me know if you find any problem.

Hello @josuemtzmo, congratulation for your new position. Thanks for your attention. 
Sorry, this module is compatible with `xarray` 0.18.2,  but currently the latest version of the xarray library is v0.20.1 (5 November 2021) that it is incompatible with this version.
I think your work in writing xarrayMannKendall module is very valuable and It's worth to upgrade to a library.

**Comment by josuemtzmo** [comment]
Fixed. For reference, the issue was solved by forcing the `.values` on the coordinates that construct the trend dataset:
https://github.com/josuemtzmo/xarrayMannKendall/blob/405d1e3f2b9a1bca88ae06c8d2dd96ac806ac9c5/xarrayMannKendall/xarrayMannKendall.py#L233-L239
and 
https://github.com/josuemtzmo/xarrayMannKendall/blob/405d1e3f2b9a1bca88ae06c8d2dd96ac806ac9c5/xarrayMannKendall/xarrayMannKendall.py#L225-L226

**Comment by NILICK** [comment]
> Fixed. For reference, the issue was solved by forcing the `.values` on the coordinates that construct the trend dataset:
> 
> https://github.com/josuemtzmo/xarrayMannKendall/blob/405d1e3f2b9a1bca88ae06c8d2dd96ac806ac9c5/xarrayMannKendall/xarrayMannKendall.py#L233-L239
> 
> and
> 
> https://github.com/josuemtzmo/xarrayMannKendall/blob/405d1e3f2b9a1bca88ae06c8d2dd96ac806ac9c5/xarrayMannKendall/xarrayMannKendall.py#L225-L226

Thanks for your attention, now it works with xarray=0.20.1 correctly.
