### ISSUE TITLE
Tag new patch release?

### ISSUE THREAD

**Issue by navidcy** [josuemtzmo/xarrayMannKendall#5]
After bug fix #4 should we tag a new patch release and push to conda?

cc @julia-neme

**Comment by josuemtzmo** [comment]
I've done a new release and now it can be installed using pip:

```pip install xarrayMannKendall```

The process to get it into conda is a bit longer. I'm working on it.

**Comment by josuemtzmo** [comment]
For more info: 
https://github.com/conda-forge/staged-recipes/pull/17745#issue-1116073980
