### ISSUE TITLE
Conda badge in `README`

### ISSUE THREAD

**Issue by navidcy** [josuemtzmo/xarrayMannKendall#6]
Should we add one?

**Comment by josuemtzmo** [comment]
No until it's published.

**Comment by josuemtzmo** [comment]
xarrayMannKendall has been merged into conda-forge, so in a couple of days it should be able to install it using:
```
conda install -c conda-forge xarrayMannKendall
```

**Comment by navidcy** [comment]
Really? Still after a few days already it needs few days more?

When I tag a new release of a Julia package it takes about 10-15 min to be merged and be available to bd installed by anyone over the globe.

**Comment by josuemtzmo** [comment]
Don't know dude, it may be in a few hours, it was merged, but now it needs to build...

**Comment by navidcy** [comment]
Yeah. It's already been 4 days tho.
