### ISSUE TITLE
Tags vs Releases

### ISSUE THREAD

**Issue by navidcy** [josuemtzmo/xarrayMannKendall#9]
@josuemtzmo, I see you tagged this package for up to 1.4.3 but only made one release in GitHub. Should we remedy that? (I don't have strong opinion -- I'm just wondering.)

**Comment by navidcy** [comment]
@aidanheerdegen, do you have an opinion on this? Does tags vs releases affect the version that the package gets installed, e.g., in the conda env on NCI?

**Comment by aidanheerdegen** [comment]
Release is a GitHub concept, and while it can mean many things to many people, essentially it boils down to creating some files that can be downloaded with a release number, a form of publishing. Similar to a `pypi` package.

`conda` packages are yet another independent way of publishing code, making it available for download/installation.

I see @josuemtzmo has added `xarraymannkendall` to `conga-forge`, so I'll delete the older version from the `coecms` channel so the `conda` environment picks up the latest version.
